# Generated by Django 4.2.30 on 2026-07-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Price in cents (e.g., 50 = $0.50, 3300 = $33.00). Stripe minimum is 50.'),
        ),
    ]
